# Generated by Django 5.1.6 on 2025-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': 'external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectEquipments',
            fields=[
                ('project_equipment_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_equipment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_equipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_role_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_project_description', models.TextField(blank=True, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectWarranty',
            fields=[
                ('project_warranty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warranty_coverage_yr', models.IntegerField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
            ],
            options={
                'db_table': 'external_project_warranty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.TextField()),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectLabor',
            fields=[
                ('intrnl_project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_job_role_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'internal_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('target_starting_date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_budget_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_project_request',
                'managed': False,
            },
        ),
    ]
