# Generated by Django 5.1.6 on 2025-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('project_milestone', models.CharField(choices=[('planning', 'Planning'), ('design', 'Design'), ('implementation', 'Implementation'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('maintenance', 'Maintenance')], max_length=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('estimated_end_date', models.DateField(null=True)),
                ('warranty_coverage_yr', models.IntegerField(null=True)),
                ('warranty_start_date', models.DateField(null=True)),
                ('warranty_end_date', models.DateField(null=True)),
                ('project_issues', models.TextField(null=True)),
                ('warranty_status', models.CharField(choices=[('not started', 'Not Started'), ('active', 'Active'), ('expired', 'Expired')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectEquipments',
            fields=[
                ('project_equipment_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('project_equipment_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_equipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50, null=True)),
                ('ext_project_description', models.TextField(null=True)),
                ('approval_id', models.CharField(max_length=255, null=True)),
                ('item_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_request_id', models.CharField(max_length=255, null=True)),
                ('intrnl_project_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('approval_id', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('estimated_end_date', models.DateField(null=True)),
                ('project_issues', models.TextField(null=True)),
            ],
            options={
                'db_table': 'project_management.internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('request_date', models.DateField()),
                ('employee_id', models.CharField(max_length=255, null=True)),
                ('dept_id', models.CharField(max_length=255, null=True)),
                ('reason_for_request', models.TextField(null=True)),
                ('materials_needed', models.TextField(null=True)),
                ('equipments_needed', models.TextField(null=True)),
                ('project_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('upgrade', 'Upgrade'), ('expansion', 'Expansion'), ('research', 'Research'), ('other', 'Other')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'project_management.internal_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCosts',
            fields=[
                ('project_resources_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('bom_id', models.CharField(max_length=255, null=True)),
                ('budget_approvals_id', models.CharField(max_length=255, null=True)),
                ('intrnl_project_id', models.CharField(max_length=255, null=True)),
                ('outside_labor_costs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('utility_costs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('outsourced_costs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('overall_project_costs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'project_management.project_costs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('job_role_needed', models.CharField(max_length=255, null=True)),
                ('employee_id', models.CharField(max_length=255, null=True)),
                ('intrnl_project_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('task_description', models.TextField(null=True)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('task_deadline', models.DateField()),
                ('project_labor_id', models.CharField(max_length=255, null=True)),
                ('intrnl_project_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.project_tasks',
                'managed': False,
            },
        ),
    ]
