# Generated by Django 5.1.6 on 2025-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': 'external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTracking',
            fields=[
                ('project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_milestone', models.TextField()),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'external_project_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
            ],
            options={
                'db_table': 'external_project_warranty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.TextField()),
            ],
            options={
                'db_table': 'internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'internal_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'internal_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTaskList',
            fields=[
                ('intrnl_task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_task_description', models.TextField(blank=True, null=True)),
                ('intrnl_task_status', models.TextField()),
                ('intrnl_task_deadline', models.DateField()),
            ],
            options={
                'db_table': 'internal_project_task_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTracking',
            fields=[
                ('intrnl_project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_start_date', models.DateField()),
                ('intrnl_estimated_end_date', models.DateField()),
                ('intrnl_project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_project_tracking',
                'managed': False,
            },
        ),
    ]
