# Generated by Django 5.1.6 on 2025-04-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': 'external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50)),
                ('ext_project_description', models.TextField(blank=True, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTracking',
            fields=[
                ('project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_milestone', models.TextField()),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'external_project_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectWarranty',
            fields=[
                ('project_warranty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warranty_coverage_yr', models.IntegerField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
            ],
            options={
                'db_table': 'external_project_warranty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.TextField()),
            ],
            options={
                'db_table': 'internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('request_valid_date', models.DateField()),
                ('request_starting_date', models.DateField()),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.TextField()),
            ],
            options={
                'db_table': 'internal_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTracking',
            fields=[
                ('intrnl_project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_start_date', models.DateField()),
                ('intrnl_estimated_end_date', models.DateField()),
                ('intrnl_project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_project_tracking',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProjectPlan',
        ),
    ]
