# Generated by Django 5.1.6 on 2025-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'human_resources.employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
                ('project_milestone', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('warranty_coverage_yr', models.IntegerField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('project_issues', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_project_description', models.TextField(blank=True, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.TextField()),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('project_issues', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_management.internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('target_starting_date', models.DateField(blank=True, null=True)),
                ('project_budget_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_budget_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_management.internal_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementApproval',
            fields=[
                ('approval_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'management.management_approvals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_role_needed', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.TextField()),
                ('task_deadline', models.DateField()),
            ],
            options={
                'db_table': 'project_management.project_tasks',
                'managed': False,
            },
        ),
    ]
