# Generated by Django 5.1.6 on 2025-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_status', models.CharField(max_length=50)),
                ('project_milestone', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('warranty_coverage_yr', models.IntegerField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('project_issues', models.TextField(blank=True, null=True)),
                ('warranty_status', models.CharField(blank=True, default='not started', max_length=50, null=True)),
            ],
            options={
                'db_table': 'project_management"."external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management"."external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('project_status', models.CharField(blank=True, max_length=50, null=True)),
                ('project_milestone', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_status', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project_management"."external_projects_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectWarrantyView',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_coverage_yr', models.IntegerField(blank=True, null=True)),
                ('warranty_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project_management"."project_warranty_view',
                'managed': False,
            },
        ),
    ]
