# Generated by Django 5.1.6 on 2025-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': 'external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTaskList',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Task ID')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('task_status', models.CharField(max_length=50, verbose_name='Status')),
                ('task_deadline', models.DateField(verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'External Task',
                'verbose_name_plural': 'External Tasks',
                'db_table': 'external_project_task_list',
                'ordering': ['task_deadline'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.TextField()),
            ],
            options={
                'db_table': 'internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectLabor',
            fields=[
                ('intrnl_project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'internal_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'internal_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTaskList',
            fields=[
                ('intrnl_task_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Task ID')),
                ('intrnl_task_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('intrnl_task_status', models.CharField(max_length=50, verbose_name='Status')),
                ('intrnl_task_deadline', models.DateField(verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Internal Task',
                'verbose_name_plural': 'Internal Tasks',
                'db_table': 'internal_project_task_list',
                'ordering': ['intrnl_task_deadline'],
                'managed': False,
            },
        ),
    ]
