# Generated by Django 5.1.6 on 2025-04-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='externalprojecttasklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='internalprojecttasklist',
            options={'managed': False},
        ),
    ]
