# Generated by Django 5.1.6 on 2025-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0002_employees_alter_externalprojecttasklist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectTasks',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.TextField()),
                ('task_deadline', models.DateField()),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTasks',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.TextField()),
                ('task_deadline', models.DateField()),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project_management.internal_project_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job_role_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('intrnl_project_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.TextField()),
                ('task_deadline', models.DateField()),
                ('project_labor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('intrnl_project_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.project_tasks',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ExternalProjectLabor',
        ),
        migrations.DeleteModel(
            name='ExternalProjectTaskList',
        ),
        migrations.DeleteModel(
            name='InternalProjectLabor',
        ),
        migrations.DeleteModel(
            name='InternalProjectTaskList',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='human_resources.employees',
        ),
        migrations.AlterModelTable(
            name='externalprojectdetails',
            table='project_management.external_project_details',
        ),
        migrations.AlterModelTable(
            name='externalprojectrequest',
            table='project_management.external_project_request',
        ),
        migrations.AlterModelTable(
            name='internalprojectdetails',
            table='project_management.internal_project_details',
        ),
        migrations.AlterModelTable(
            name='internalprojectrequest',
            table='project_management.internal_project_request',
        ),
    ]
