# Generated by Django 5.1.6 on 2025-03-24 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProjectLabor',
            fields=[
                ('intrnl_project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_management.internal_project_labor',
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_management.internal_project_request',
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('project_request_id', models.ForeignKey(blank=True, db_column='project_request_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='project_request.internalprojectrequest')),
            ],
            options={
                'db_table': 'project_management.internal_project_details',
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTaskList',
            fields=[
                ('intrnl_task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_task_description', models.TextField(blank=True, null=True)),
                ('intrnl_task_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('intrnl_task_deadline', models.DateField()),
                ('intrnl_project_id', models.ForeignKey(db_column='intrnl_project_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_request.internalprojectdetails')),
                ('intrnl_project_labor_id', models.ForeignKey(blank=True, db_column='intrnl_project_labor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='project_request.internalprojectlabor')),
            ],
            options={
                'db_table': 'project_management.internal_project_task_list',
            },
        ),
    ]
