# Generated by Django 5.1.6 on 2025-03-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalprojectdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='internalprojectlabor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='internalprojectrequest',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='InternalProjectTaskList',
        ),
    ]
