# Generated by Django 5.1.6 on 2025-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_request', '0002_alter_internalprojectdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50)),
                ('ext_project_description', models.TextField(blank=True, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_management.external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'project_management.project_status',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='internalprojectdetails',
            name='project_request_id',
        ),
        migrations.DeleteModel(
            name='InternalProjectLabor',
        ),
        migrations.DeleteModel(
            name='InternalProjectDetails',
        ),
    ]
