# Generated by Django 5.1.6 on 2025-03-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_request', '0004_department_employee_delete_projectstatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
