# Generated by Django 5.1.6 on 2025-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_request', '0005_delete_department_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contractual', 'Contractual')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='externalprojectrequest',
            options={'managed': False, 'verbose_name': 'External Project Request', 'verbose_name_plural': 'External Project Requests'},
        ),
        migrations.AlterModelOptions(
            name='internalprojectrequest',
            options={'managed': False, 'verbose_name': 'Internal Project Request', 'verbose_name_plural': 'Internal Project Requests'},
        ),
    ]
