# Generated by Django 5.1.6 on 2025-03-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_request', '0006_departments_employees_delete_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
