# Generated by Django 5.1.6 on 2025-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': 'external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectWarranty',
            fields=[
                ('project_warranty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warranty_coverage_yr', models.IntegerField(verbose_name='Warranty Coverage (Years)')),
                ('warranty_start_date', models.DateField(verbose_name='Start Date')),
                ('warranty_end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Project Warranty',
                'verbose_name_plural': 'Project Warranties',
                'db_table': 'external_project_warranty',
                'ordering': ['-warranty_end_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivedWarranty',
            fields=[
                ('warranty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archived_warranties',
                'managed': True,
            },
        ),
    ]
