# Generated by Django 5.1.6 on 2025-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], max_length=20)),
                ('project_milestone', models.CharField(blank=True, choices=[('planning', 'Planning'), ('design', 'Design'), ('implementation', 'Implementation'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('maintenance', 'Maintenance')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('warranty_coverage_yr', models.IntegerField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('project_issues', models.TextField(blank=True, null=True)),
                ('warranty_status', models.CharField(choices=[('not started', 'Not Started'), ('active', 'Active'), ('expired', 'Expired')], default='not started', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_management.external_project_details',
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('intrnl_project_status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], max_length=20)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('project_issues', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_management.internal_project_details',
            },
        ),
        migrations.CreateModel(
            name='ProjectCosts',
            fields=[
                ('project_resources_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bom_id', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_approvals_id', models.CharField(blank=True, max_length=255, null=True)),
                ('intrnl_project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('outside_labor_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utility_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outsourced_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_project_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'project_management.project_costs',
            },
        ),
    ]
